print("*" *28)
print("*TWO number Basic calculator*")
print("*" *28)
first_number= input("  Input your first number \n ------>")
second_number= input("Input your second number \n ------>")
answer=int(first_number)-int(second_number)
print("*"*28)
print("answer =" + str(answer))
print("*"*28)
